name: "app"

services:
  app:
    image: milkydad/main-app
    container_name: app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./env_var.js:/app/env_var.js
      - ./init-mongo.js:/app/init-mongo.js
      - app-data:/app
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=38143
      - HOST=0.0.0.0
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=appdb
    networks:
      - front
      - back
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: db
    restart: always
    env_file: [.env-mongo]
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongod.conf:/etc/mongod.conf
        #- /var/lib/docker/volumes/app_app-data/_data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - back
    command: [--auth, --port, "38143"] 
    environment:
      - MONGO_ROOT_USER=
      - MONGO_ROOT_PASSWD=
      - HASH_LOGIN=
      - HASH_PASSWD=


  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./logs:/usr/local/apache2/logs
      - /etc/letsencrypt:/etc/letsencrypt
      - app-data:/var/www/app
    command: >
      sh -c "httpd -D FOREGROUND"
    networks:
      - front
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - app-data:/var/www/app/
    command: certonly --webroot -w /var/www/app/public/html -d silk-road-store.ru --email asker_sulanov1999@mail.ru --agree-tos --verbose
    depends_on:
      - apache
    networks:
      - front

volumes:
  app-data:
  mongo-data:
  mongo-config:
networks:
  front:
  back:
