version: "3.9"
name: app

services: 
 app: 
    image: milkydad/app
    ports: 
         - "3000:3000"
    restart: always
    volumes:
         - /home/app/env_var.js:/app/env_var.js
    environment:
         - MONGO_URL=mongodb://db:27017
    networks:
         - front
         - back
    container_name: app
 mongodb:
    image: mongo
    ports:
         - "27017:27017"
    restart: always
    volumes:
         - mongodb:/data/db
    networks:
         - back
    container_name: db
 apache:
    image: httpd
    ports: 
         - "80:80"
    volumes:
         - type: bind
           source: ./app
           target: /usr/local/apache2/htdocs/app
         - type: bind
           source: /home/app/httpd.conf
           target: /usr/local/apache2/conf/httpd.conf
         - ./logs:/usr/local/apache2/logs
    networks:
         - front
    container_name: apache

volumes:
     mongodb:
networks:
        front:
        back:
