version: "3.8"
name: "bot"

services:
  app:
    container_name: bot
    image: milkydad/bot
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: /home/bot/env.js
        target: /bot/env.js
    restart: always
    environment:
      - MONGO_URL=mongodb://db:27017
  db:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: always

volumes:
  mongodb:

