ServerRoot /usr/local/apache2/
ServerName silk-road-store.ru

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module /usr/local/apache2/modules/mod_proxy_http.so
LoadModule proxy_balancer_module /usr/local/apache2/modules/mod_proxy_balancer.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule lbmethod_byrequests_module /usr/local/apache2/modules/mod_lbmethod_byrequests.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so

Timeout 600

<IfModule !mpm_prefork_module>
    #LoadModule cgid_module modules/mod_cgid.so
</IfModule>
<IfModule mpm_prefork_module>
    #LoadModule cgi_module modules/mod_cgi.so
</IfModule>

<IfModule unixd_module>
    User www-data
    Group www-data
</IfModule>

ServerAdmin asker_sultanov1999@mail.ru
DocumentRoot /var/www/app/public/html/

<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

<Files ".ht*">
    Require all denied
</Files>


<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    CustomLog /usr/local/apache2/logs/access.log combined
</IfModule>

<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
</IfModule>

<Directory "/usr/local/apache2/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>

<IfModule headers_module>
    RequestHeader unset Proxy early
</IfModule>

<Location "/.well-known/acme-challenge/">
    ProxyPass !
</Location>

Alias /.well-known/acme-challenge /var/www/app/public/html/.well-known/acme-challenge
<Directory /var/www/app/public/html/.well-known/acme-challenge>
    AllowOverride None
    Require all granted
</Directory>

<IfModule mime_module>
    TypesConfig conf/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>

Listen 80
<VirtualHost *:80>
    ServerName silk-road-store.ru
    ServerAlias www.silk-road-store.ru
    ServerAdmin asker_sultanov1999@mail.ru

    DocumentRoot  /var/www/app/public/html/

    <Directory  /var/www/app/public/html/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted

        <FilesMatch "\.(css|js|ico)$">
            Require all granted
        </FilesMatch>

    </Directory>

    ErrorLog /usr/local/apache2/logs/error.log
    CustomLog /usr/local/apache2/logs/access.log combined

    ProxyPass / http://app:3000/
    ProxyPassReverse / http://app:3000/
    ProxyRequests off
</VirtualHost>


Listen 443
<VirtualHost *:443>
        ServerName  silk-road-store.ru
        ServerAlias www.silk-road-store.ru
        ServerAdmin asker_sultanov1999@mail.ru

        DocumentRoot /var/www/app/public/html

 <Directory "/var/www/app/public/html" >
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
 </Directory>
        ErrorLog /usr/local/apache2/logs/error.log
        CustomLog /usr/local/apache2/logs/access.log combined

        ProxyPass / http://app:3000/
        ProxyPassReverse / http://app:3000/
        ProxyRequests off

      SSLEngine on
      SSLCertificateFile /etc/letsencrypt/live/silk-road-store.ru/fullchain.pem
      SSLCertificateKeyFile /etc/letsencrypt/live/silk-road-store.ru/privkey.pem
</VirtualHost>

